[package]
name = "spice-sys"
version = "0.0.1"
authors = ["Rolfe Power <rolfepower4@gmail.com>"]
edition = "2018"
description = "Rust wrapper for the spice ephemeris library from NAIF"
homepage = "https://github.com/rjpower4/spice-sys"
build = "build.rs"

[dependencies]
libc = "0.2.69"
